2023-10-30 13:03:45,023	[INFO]	/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/utils/autoreload.py(Line:677)	Watching for file changes with StatReloader
2023-10-30 13:03:52,334	[ERROR]	/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/core/handlers/exception.py(Line:124)	Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2023-10-30 13:03:52,336	[WARNING]	/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/utils/log.py(Line:241)	Bad Request: /
2023-10-30 13:03:52,336	[WARNING]	/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/core/servers/basehttp.py(Line:187)	"GET / HTTP/1.1" 400 143
2023-10-30 13:03:53,203	[ERROR]	/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/core/handlers/exception.py(Line:124)	Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2023-10-30 13:03:53,204	[WARNING]	/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/utils/log.py(Line:241)	Bad Request: /favicon.ico
2023-10-30 13:03:53,204	[WARNING]	/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/core/servers/basehttp.py(Line:187)	"GET /favicon.ico HTTP/1.1" 400 143
2023-10-30 13:04:04,445	[ERROR]	/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/core/handlers/exception.py(Line:124)	Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2023-10-30 13:04:04,446	[WARNING]	/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/utils/log.py(Line:241)	Bad Request: /
2023-10-30 13:04:04,446	[WARNING]	/Users/kunieda/Library/CloudStorage/Dropbox/PythonsWin/venvmac/lib/python3.10/site-packages/django/core/servers/basehttp.py(Line:187)	"GET / HTTP/1.1" 400 143
